data:
  data_dir: ../datasets/scannetpp/
  dataset: ScanNetPP
  unconditional: true
  workers: 4
  npoints: 50000
  nc: 3
  voxel_size: 0.01
  upsample_frac: 8
  normalize: true
diffusion:
  timesteps: 1000
  timesteps_clip: 100
  sampling_timesteps: 1000
  formulation: LUCID
  objective: pred_v
  schedule: cosine
  min_snr_gamma: 5
  sampling_strategy: DDPM
  ddim_sampling_eta: 0.0
  sampling_hint: true
  loss_type: mse
  dynamic_threshold: true
  clip: true
  beta_start: 0.0001
  beta_end: 0.02
  reg_scale: 0
model:
  type: PVD
  in_dim: 3
  extra_feature_channels: 0
  out_dim: 3
  time_embed_dim: 64
  use_attention: false
  dropout: 0.1
  EMA:
    decay: 0.999
  ST:
    fdim: 256
    inducers: 128
    layers: 6
  Mink:
    init_ds_factor: 4
    D: 1
    dim_mults:
    - 1
    - 2
    - 4
    - 8
    downsampfactors:
    - 4
    - 4
    - 4
    - 4
training:
  optimizer:
    type: AdamW
    lr: 0.0001
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.0
  scheduler:
    type: constant
    lr_gamma: 0.999
  grad_clip:
    enabled: false
    value: 10.0
  bs: 16
  overfit: false
  amp: false
  steps: 50000
  accumulation_steps: 2
  log_interval: 10
  save_interval: 10
  viz_interval: 10
  seed: 42
sampling:
  bs: 16
  num_iter: 1
config: configs/scannet_cut_pvd.yml
name: scannet_cut_pvd
save_dir: checkpoints
model_path: ''
world_size: 1
dist_url: tcp://127.0.0.1:9991
dist_backend: nccl
distribution_type: single
rank: 0
