data:
  data_dir: ../3d/
  dataset: "Indoor"
  workers: 4
  npoints: 16384
  voxel_size: 0.01
  nc: 3 # number of features (x, y, z)
  upsample_frac: 8 # when downsampling from the ground truth
  batch_size_eval: 1
  normalize: true # this is normalization to 0-1
diffusion:
  timesteps: 1000
  sampling_timesteps: 50
  formulation: PVD # PVD ¦ LUCID ¦ EDM
  objective: pred_v # pred_noise ¦ pred_v ¦ pred_x0
  schedule: sigmoid # linear ¦ sigmoid ¦ cosine
  min_snr_gamma: 5
  sampling_strategy: DDIM
  ddim_sampling_eta: 0.
  loss_type: mse
  clip: true
  dynamic_threshold: false
  beta_start: 0.0001
  beta_end: 0.02
  reg_scale: 0
model:
  type: SetTransformer # Mink ¦ PVD
  in_dim: 3
  extra_feature_channels: 0 # no extra dim => append the points not features
  out_dim: 3
  time_embed_dim: 64
  use_attention: true
  dropout: 0.1
  EMA:
    decay: 0.999
  ST:
    fdim: 256
    inducers: 1024
    layers: 6
training:
  optimizer:
    type: AdamW
    lr: 2.e-4
    beta1: 0.9
    beta2: 0.99
    weight_decay: 0.
  scheduler:
    type: constant
    lr_gamma: 0.999
  grad_clip:
    enabled: false
    value: 10.0
  bs: 4
  accumulation_steps: 4
  overfit: false
  amp: true
  steps: 100000
  log_interval: 10
  save_interval: 1000
  viz_interval: 1000
  seed: 42
sampling:
  bs: 1
  num_iter: 1




