data:
  data_dir: ../datasets/scannetpp/
  dataset: "ScanNetPP"
  unconditional: true
  workers: 4
  npoints: 50000
  nc: 3 # number of features (x, y, z)
  voxel_size: 0.01
  upsample_frac: 8 # when downsampling from the ground truth
  normalize: true # unit cube/sphere normalization
diffusion:
  timesteps: 1000
  timesteps_clip: 100
  sampling_timesteps: 1000
  formulation: LUCID # PVD ¦ LUCID ¦ EDM
  objective: pred_v # pred_noise ¦ pred_v ¦ pred_x0
  schedule: cosine # linear ¦ sigmoid ¦ cosine
  min_snr_gamma: 5
  sampling_strategy: DDPM
  ddim_sampling_eta: 0.
  sampling_hint: true
  loss_type: mse
  dynamic_threshold: true
  clip: true
  beta_start: 0.0001
  beta_end: 0.02
  reg_scale: 0
model:
  type: PVD # Mink ¦ PVD
  in_dim: 3
  extra_feature_channels: 0
  out_dim: 3
  time_embed_dim: 64
  use_attention: true
  dropout: 0.1
  EMA:
    decay: 0.999
  ST:
    fdim: 256
    inducers: 128
    layers: 6
  Mink:
    init_ds_factor: 2
    D: 1
    dim_mults: [1, 2, 4, 8]
    downsampfactors: [4, 4, 4, 4]
training:
  optimizer:
    type: AdamW
    lr: 1.e-4
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.0
  scheduler:
    type: constant
    lr_gamma: 0.999
  grad_clip:
    enabled: false
    value: 10.0
  bs: 16
  overfit: false
  amp: false
  steps: 300_000
  accumulation_steps: 2
  log_interval: 10 # steps
  save_interval: 5000
  viz_interval: 5000
  seed: 42
sampling:
  bs: 16
  num_iter: 1
