data:
  data_dir: /cluster/project/cvg/Shared_datasets/scannetpp/data/
  dataset: "ScanNetPP"
  features: dino
  unconditional: true
  workers: 4
  npoints: 8192
  nc: 3 # number of features (x, y, z)
  voxel_size: 0.01
  upsample_frac: 8 # when downsampling from the ground truth
  normalize: true # unit cube/sphere normalization
diffusion:
  timesteps: 200
  timesteps_clip: 200
  sampling_timesteps: 200
  formulation: LUCID # PVD ¦ LUCID ¦ EDM
  objective: pred_noise # pred_noise ¦ pred_v ¦ pred_x0
  schedule: linear # linear ¦ sigmoid ¦ cosine
  min_snr_gamma: 5
  sampling_strategy: DDPM
  ddim_sampling_eta: 0.
  sampling_hint: true
  loss_type: l1
  dynamic_threshold: false
  clip: false
  beta_start: 1.e-7
  beta_end: 1.e-7
  reg_scale: 0
model:
  type: PVD # Mink ¦ PVD
  ema: false
  in_dim: 3
  extra_feature_channels: 0
  out_dim: 3
  time_embed_dim: 64
  dropout: 0.1
  EMA:
    decay: 0.999
  PVD:
    use_attention: true
    size: large
    use_st: false
  ST:
    fdim: 256
    inducers: 128
    layers: 6
  Mink:
    init_ds_factor: 2
    D: 1
    dim_mults: [1, 2, 4, 8]
    downsampfactors: [4, 4, 4, 4]
training:
  optimizer:
    type: AdamW
    lr: 1.e-4
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.0
  scheduler:
    type: constant
    lr_gamma: 0.999
  grad_clip:
    enabled: false
    value: 10.0
  bs: 32
  overfit: false
  amp: false
  steps: 100_000
  accumulation_steps: 1
  log_interval: 10 # steps
  save_interval: 10000
  viz_interval: 10000
  seed: 42
sampling:
  bs: 32
  num_iter: 1
