data:
  data_dir: /home/mathi/data/snpp_processed/
  dataset: "ScanNetPP_iPhone"
  augment: true
  point_features: none
  use_rgb_features: true
  unconditional: false
  workers: 4
  npoints: 8192
  nc: 3 # number of features (x, y, z)
  voxel_size: 0.01
  upsample_frac: 8 # when downsampling from the ground truth
  normalize: true # unit cube/sphere normalization
diffusion:
  timesteps: 400
  timesteps_clip: 400
  sampling_timesteps: 10
  formulation: i2sb # PVD ¦ LUCID ¦ EDM
  objective: pred_noise # pred_noise ¦ pred_v ¦ pred_x0
  schedule: linear # linear ¦ sigmoid ¦ cosine
  min_snr_gamma: 5
  sampling_strategy: DDPM
  ddim_sampling_eta: 0.
  sampling_hint: false
  loss_type: mse
  dynamic_threshold: false
  clip: false
  beta_start: 1.e-7
  beta_end: 1.e-6
  beta_max: 1.e-7
  ot_ode: true
  reg_scale: 0
model:
  type: PVD # Mink ¦ PVD
  ema: false
  in_dim: 3
  extra_feature_channels: 3 # 3 RGB + 384 (DINO)
  out_dim: 3
  time_embed_dim: 64
  dropout: 0.1
  EMA:
    decay: 0.999
  PVD:
    attention_type: linear
    attention_heads: 12
    size: large
    attentions: [0, 0, 0, 1, 1]
    channels: [256, 256, 512, 512, 1024]
    voxel_resolutions: [32, 16, 8, 8]
    n_sa_blocks: [1, 2, 3, 4]
    n_fp_blocks: [1, 2, 3, 4]
    radius: [0.1, 0.2, 0.4, 0.8]
    out_mlp: 128
  ST:
    fdim: 256
    inducers: 128
    layers: 6
  Mink:
    init_ds_factor: 2
    D: 1
    dim_mults: [1, 2, 4, 8]
    downsampfactors: [4, 4, 4, 4]
training:
  optimizer:
    type: AdamW
    lr: 1.e-4
    beta1: 0.9
    beta2: 0.999
    weight_decay: 1.e-5
  scheduler:
    type: constant
    lr_gamma: 0.999
  grad_clip:
    enabled: false
    value: 10.0
  bs: 4
  overfit: false
  amp: true
  steps: 500_000
  accumulation_steps: 1
  log_interval: 10 # steps
  save_interval: 10000
  viz_interval: 10000
  seed: 42
sampling:
  bs: 4
  num_iter: 1
